(****************************************************************************


resource.pas

produced by Borland Resource Workshop


*****************************************************************************)

unit resource;

interface

const

	Dlg_Details	=	100;
	id_ImageWidth	=	100;
	id_ImageHeight	=	101;
	id_ImageSize	=	102;
        id_NumberOfColors       = 103;
	id_ImageFormat	=	104;
	id_Compression	=	105;
	id_PreviewButton	=	110;
	id_AboutBox	=	111;
	id_PreviewArea	=	120;
implementation

end.
